name: Basic Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        type: number
        description: 'Add a number'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Print the number
        run: echo version = ${{ inputs.version }}