name: Test Workflow

on:
  push:

permissions:
  contents: write
  id-token: write # This is required for aws oidc connection
  pull-requests: write

jobs:
  test-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check vars
        run: |         
          TF_VARS_token = ${{ vars.token }}
          
          echo "check the value" 
          echo "$TF_VARS_token"
