name: Test Workflow

on:
  push:

permissions:
  contents: write
  id-token: write # This is required for aws oidc connection
  pull-requests: write

jobs:
  test-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check vars
        run: |         
          export TF_VARS_token = $(cat <<EOF ${{ vars.token }} EOF) 
          
          echo "check the value" 
          echo "$TF_VARS_token"
  
  
  

#  export TF_VARS_iot_input_ca_cert=$(cat <<EOF
#  -----BEGIN PUBLIC KEY-----
#  sajldlkuewindasmASL/aisudoiasumasdnowqeuoi@kajsdlkausKJDolkejpwr
#  sajldlkuewindasmASL/aisudoiasumasdnowqeuoi@kajsdlkausKJDolkejpwr
#  sajldlkuewindasmASL/aisudoiasumasdnowqeuoi@kajsdlkausKJDolkejpwr
#  sajldlkuewindasmASL/aisudoiasumasdnowqeuoi@kajsdlkausKJDolkejpwr
#  sajldlkuewindasmASL/aisudoiasumasdnowqeuoi@kajsdlkausKJDolkejpwr
#  sajldlkuewindasmASL/aisudoiasumasdnowqeuoi@kajsdlkausKJDolkejpwr
#  asdhjasd
#  -----END PUBLIC KEY-----