name: Test Workflow

on:
  push:

permissions:
  contents: write
  id-token: write # This is required for aws oidc connection
  pull-requests: write

jobs:
  test-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check vars
        run: |
          # Use a heredoc to assign the multi-line variable
          TF_VARS_token=$(cat <<'EOF'
          ${{ vars.token }}
          EOF
          )
          echo "Let's print"
          echo "$TF_VARS_token"
  
  
