name: "Terraform Apply Pipeline"

on:
  workflow_call:
    inputs:
      VARS:
        type: string

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  tf-apply:
    name: tf-apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Env
        run: |
          echo ${{ inputs.VARS }}
          echo '${{ inputs.VARS }}' > vars.json
          jq -r 'to_entries[] | "\(.key)=\(.value)"' vars.json >> $GITHUB_ENV

      - name: Verify Env Variables
        run: |
          echo "TF_VAR_role_name=$TF_VAR_role_name"
          echo "TF_VAR_role_id=$TF_VAR_role_id"