name: "Terraform Apply Pipeline"

on:
  workflow_call:
    inputs:
      VARS:
        required: true
        type: map

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  tf-apply:
    name: tf-apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Env
        run: |
          echo ${ inputs.VARS }