name: Use Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/terraform-reusable.yaml
    with:
      VARS:
        first: "jay"
        last: "Bhavsar"