name: Use Reusable Workflow

on:
  push:
    branches:
      - main

permissions:
  pull-request: write
  id-token: write

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/terraform-reusable.yaml
    with:
      VARS: '{"TF_VAR_role_name": "x", "TF_VAR_role_id": "333"}'
