name: Use Reusable Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/terraform-reusable.yaml
    with:
      VARS: '{"TF_VAR_role_name": "x", "TF_VAR_role_id": "333"}'
